version: '3.8'

services:
  uptime-kabomba:
    container_name: uptime-kabomba-dev
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../data:/data
    ports:
      - "8080:8080"  # <Host Port>:<Container Port>
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_DSN=/data/uptime-kabomba.db

